import { useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeftIcon, ArchiveBoxIcon, CalendarDotsIcon, CrosshairSimpleIcon, FingerprintIcon, LockKeyIcon, PauseIcon, PlayIcon, PlusIcon, SlidersHorizontalIcon, TerminalWindowIcon } from "@phosphor-icons/react";
import type { Artifact, Project, Run, Schedule, SkillSnapshot, WorkSpec } from "@personal-os/vnext-contracts";
import { Link } from "wouter";
import { api, patch, post } from "../api";
import { EmptyBlock, ErrorBlock, Field, LoadingBlock, PageHeader, Status, errorMessage, formatDate } from "../components";

export function RadarPage({ selectedId }: { selectedId?: string } = {}) {
  const client = useQueryClient();
  const [composer, setComposer] = useState<"workflow" | "schedule" | null>(null);
  const [editingScheduleId, setEditingScheduleId] = useState<string | null>(null);
  const specs = useQuery({ queryKey: ["work-specs"], queryFn: () => api<WorkSpec[]>("/work-specs") });
  const schedules = useQuery({ queryKey: ["schedules"], queryFn: () => api<Schedule[]>("/schedules") });
  const projects = useQuery({ queryKey: ["projects"], queryFn: () => api<Project[]>("/projects") });
  const runs = useQuery({ queryKey: ["runs"], queryFn: () => api<Run[]>("/runs?limit=500") });
  const artifacts = useQuery({ queryKey: ["artifacts"], queryFn: () => api<Artifact[]>("/artifacts?limit=500") });
  const skills = useQuery({ queryKey: ["skills"], queryFn: () => api<SkillSnapshot[]>("/skills") });
  const refresh = () => { void client.invalidateQueries({ queryKey: ["work-specs"] }); void client.invalidateQueries({ queryKey: ["schedules"] }); void client.invalidateQueries({ queryKey: ["runs"] }); };
  const createWorkflow = useMutation({ mutationFn: (input: unknown) => post<WorkSpec>("/work-specs", input), onSuccess: () => { refresh(); setComposer(null); } });
  const createSchedule = useMutation({ mutationFn: (input: unknown) => post<Schedule>("/schedules", input), onSuccess: () => { refresh(); setComposer(null); } });
  const updateSchedule = useMutation({ mutationFn: ({ id, input }: { id: string; input: unknown }) => patch<Schedule>(`/schedules/${id}`, input), onSuccess: () => { refresh(); setEditingScheduleId(null); } });
  const action = useMutation({ mutationFn: ({ id, verb }: { id: string; verb: string }) => post(`/schedules/${id}/${verb}`), onSuccess: refresh });
  if (specs.isLoading || schedules.isLoading || projects.isLoading || runs.isLoading || artifacts.isLoading || skills.isLoading) return <LoadingBlock />;
  if (specs.error || schedules.error || projects.error || runs.error || artifacts.error || skills.error) return <ErrorBlock error={specs.error ?? schedules.error ?? projects.error ?? runs.error ?? artifacts.error ?? skills.error} />;
  const workflows = (specs.data ?? []).filter((item) => item.kind === "workflow" && item.lifecycleStatus !== "retired");
  const selected = selectedId ? specs.data?.find((item) => item.id === selectedId) ?? null : null;
  const selectedSchedules = (schedules.data ?? []).filter((item) => item.workSpecId === selectedId);
  return <div className="page-stack">
    <PageHeader title={selected ? selected.title : "雷达"} description={selected ? (selected.kind === "workflow" ? "查看固定 Skill 版本、调度、运行和成果。" : "这是一次性 WorkSpec，不会被生产 Schedule 复用。") : "把复杂流程先跑通，再沉淀成可以每天复用的固定执行定义。"} actions={selected ? <div className="button-group"><Link className="button secondary" href="/radar"><ArrowLeftIcon /> 全部雷达</Link>{selected.kind === "workflow" && <button className="button primary" onClick={() => setComposer("schedule")}><CalendarDotsIcon /> 添加定时</button>}</div> : <div className="button-group"><button className="button secondary" onClick={() => setComposer("schedule")}><CalendarDotsIcon /> 设置定时</button><button className="button primary" onClick={() => setComposer("workflow")}><PlusIcon /> 新建雷达</button></div>} />
    {composer === "workflow" && <WorkflowForm projects={projects.data ?? []} skills={skills.data ?? []} pending={createWorkflow.isPending} error={createWorkflow.error} onSubmit={(input) => createWorkflow.mutate(input)} />}
    {composer === "schedule" && <ScheduleForm workflows={workflows} selectedWorkSpecId={selected?.kind === "workflow" ? selected.id : undefined} pending={createSchedule.isPending} error={createSchedule.error} onSubmit={(input) => createSchedule.mutate(input)} />}
    {selectedId && !selected ? <EmptyBlock title="执行定义不存在" description="它可能来自旧链接，或已在迁移时被跳过。" action={<Link className="button secondary" href="/radar">返回雷达</Link>} /> : selected ? <RadarDetail workflow={selected} schedules={selectedSchedules} runs={(runs.data ?? []).filter((item) => item.workSpecId === selected.id)} artifacts={(artifacts.data ?? []).filter((item) => item.workSpecId === selected.id)} editingScheduleId={editingScheduleId} pending={updateSchedule.isPending || action.isPending} error={updateSchedule.error ?? action.error} onEdit={setEditingScheduleId} onUpdate={(id, input) => updateSchedule.mutate({ id, input })} onAction={(id, verb) => action.mutate({ id, verb })} /> : <>
      <section className="panel"><div className="section-heading"><div><h2>固定 Skill 版本</h2><p>原先的机会雷达只是其中一个 Workflow。每张卡片对应不可变的执行快照。</p></div></div>
        {workflows.length === 0 ? <EmptyBlock title="还没有雷达" description="先定义目标、执行器和输入，再为它添加定时规则。" /> : <div className="workflow-grid">{workflows.map((workflow) => {
          const bound = schedules.data?.filter((item) => item.workSpecId === workflow.id) ?? [];
          return <Link href={`/radar/${workflow.id}`} className="workflow-item" key={workflow.id}><div className="workflow-icon"><CrosshairSimpleIcon size={23} weight="duotone" /></div><div className="workflow-copy"><div><h3>{workflow.title}</h3><Status value={workflow.lifecycleStatus} /></div><p>{workflow.instructions.split(/\n\s*\n/, 1)[0]}</p><footer><span>{workflow.skill ? `${workflow.skill.name}@${workflow.skill.version}` : workflow.executorType}</span><span>{bound.length ? `${bound.length} 个定时规则` : "尚未定时"}</span></footer></div></Link>;
        })}</div>}
      </section>
      <ScheduleSection schedules={schedules.data ?? []} editingId={editingScheduleId} pending={updateSchedule.isPending || action.isPending} error={updateSchedule.error ?? action.error} onEdit={setEditingScheduleId} onUpdate={(id, input) => updateSchedule.mutate({ id, input })} onAction={(id, verb) => action.mutate({ id, verb })} />
    </>}
  </div>;
}

function RadarDetail({ workflow, schedules, runs, artifacts, editingScheduleId, pending, error, onEdit, onUpdate, onAction }: { workflow: WorkSpec; schedules: Schedule[]; runs: Run[]; artifacts: Artifact[]; editingScheduleId: string | null; pending: boolean; error: unknown; onEdit(id: string | null): void; onUpdate(id: string, input: unknown): void; onAction(id: string, verb: string): void }) {
  return <div className="radar-workspace"><section className="skill-lock panel"><div><LockKeyIcon weight="duotone" /><span><small>{workflow.skill ? `${workflow.skill.name}@${workflow.skill.version}` : workflow.kind === "workflow" ? "未绑定仓库 Skill" : "一次性 WorkSpec"}</small><strong>{workflow.skill?.contentHash ?? workflow.id}</strong></span></div><Status value={workflow.lifecycleStatus} /><p>{workflow.skill ? `固定来源 ${workflow.skill.path}；内容 SHA-256 与 WorkSpec 一同保存，Schedule 只绑定这个精确快照。` : "这是迁移前定义；新建 Agent Workflow 时应选择仓库 Skill。"}</p></section>
    <div className="radar-detail-grid"><section className="panel definition-panel"><div className="section-heading"><div><h2>执行快照</h2><p>这是 Runtime 每次运行都会接收的固定方法。</p></div></div><dl><div><dt><TerminalWindowIcon /> Runtime</dt><dd>{workflow.executorType}</dd></div><div><dt><FingerprintIcon /> 类型</dt><dd>{workflow.kind === "workflow" ? "可复用 Workflow" : "一次性工作"}</dd></div><div><dt>超时</dt><dd>{workflow.timeoutSeconds} 秒</dd></div><div><dt>最大尝试</dt><dd>{workflow.maxAttempts} 次</dd></div></dl><h3>执行要求</h3><pre>{workflow.instructions}</pre><h3>固定输入</h3><pre>{JSON.stringify(workflow.input, null, 2)}</pre></section>
      <section className="panel"><div className="section-heading"><div><h2>最近运行</h2><p>每次尝试都有独立状态、日志和验收。</p></div><Link href="/runs">打开运行中心</Link></div><div className="entity-stack">{runs.slice(0, 8).map((run) => <Link href={`/runs/${run.id}`} key={run.id}><span><strong>尝试 {run.attempt}</strong><small>{formatDate(run.createdAt)} · {run.executorType}</small></span><Status value={run.status} /></Link>)}{runs.length === 0 && <p className="quiet">这个版本还没有运行记录。</p>}</div></section>
      <section className="panel"><div className="section-heading"><div><h2>成果</h2><p>报告、代码和外部文件均可反向追踪。</p></div></div><div className="entity-stack">{artifacts.slice(0, 8).map((artifact) => <Link href={`/assets/artifacts/${artifact.id}`} key={artifact.id}><span><strong>{artifact.name}</strong><small>{artifact.uri}</small></span><ArchiveBoxIcon /></Link>)}{artifacts.length === 0 && <p className="quiet">这个版本还没有登记成果。</p>}</div></section>
    </div>
    {workflow.kind === "workflow" && <ScheduleSection schedules={schedules} editingId={editingScheduleId} pending={pending} error={error} onEdit={onEdit} onUpdate={onUpdate} onAction={onAction} />}
  </div>;
}

function ScheduleSection({ schedules, editingId, pending, error, onEdit, onUpdate, onAction }: { schedules: Schedule[]; editingId: string | null; pending: boolean; error: unknown; onEdit(id: string | null): void; onUpdate(id: string, input: unknown): void; onAction(id: string, verb: string): void }) {
  return <section className="panel"><div className="section-heading"><div><h2>定时执行</h2><p>Scheduler 到期只创建 Run；修改规则不会改变绑定的 Skill 版本。</p></div></div>
    <div className="schedule-table">{schedules.map((schedule) => editingId === schedule.id ? <ScheduleEditForm key={schedule.id} schedule={schedule} pending={pending} error={error} onCancel={() => onEdit(null)} onSubmit={(input) => onUpdate(schedule.id, input)} /> : <div className="schedule-row" key={schedule.id}><div><strong>{schedule.name}</strong><small>{schedule.cronExpression} · {schedule.timezone}{schedule.catchUp ? " · 补跑一次" : " · 不补跑"}</small></div><div><span>下次 {formatDate(schedule.nextRunAt)}</span><Status value={schedule.enabled ? "active" : "paused"} /></div><div className="row-actions"><button className="icon-button" title="修改定时" aria-label={`修改 ${schedule.name}`} onClick={() => onEdit(schedule.id)}><SlidersHorizontalIcon /></button><button className="icon-button" title={schedule.enabled ? "暂停" : "恢复"} aria-label={`${schedule.enabled ? "暂停" : "恢复"} ${schedule.name}`} onClick={() => onAction(schedule.id, schedule.enabled ? "pause" : "resume")}>{schedule.enabled ? <PauseIcon /> : <PlayIcon />}</button><button className="button secondary small" onClick={() => onAction(schedule.id, "run-now")}>立即运行</button></div></div>)}{schedules.length === 0 && <p className="quiet">还没有定时规则。</p>}</div>{Boolean(error) && !editingId && <p className="form-error">{errorMessage(error, "定时操作失败")}</p>}
  </section>;
}

function ScheduleEditForm({ schedule, pending, error, onCancel, onSubmit }: { schedule: Schedule; pending: boolean; error: unknown; onCancel(): void; onSubmit(input: unknown): void }) {
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); onSubmit({ name: data.get("name"), cronExpression: data.get("cronExpression"), timezone: data.get("timezone"), catchUp: data.get("catchUp") === "on", enabled: data.get("enabled") === "on" }); };
  return <form className="schedule-edit" onSubmit={submit}><div className="form-grid"><Field label="名称"><input name="name" defaultValue={schedule.name} required /></Field><Field label="Cron"><input name="cronExpression" defaultValue={schedule.cronExpression} required /></Field><Field label="时区"><input name="timezone" defaultValue={schedule.timezone} required /></Field><Field label="运行策略"><label className="check-field"><input type="checkbox" name="catchUp" defaultChecked={schedule.catchUp} /> 错过后补跑一次</label><label className="check-field"><input type="checkbox" name="enabled" defaultChecked={schedule.enabled} /> 启用定时</label></Field></div>{Boolean(error) && <p className="form-error">{errorMessage(error, "保存定时失败")}</p>}<div className="row-actions"><button className="button primary small" disabled={pending}>{pending ? "正在保存" : "保存修改"}</button><button className="button secondary small" type="button" onClick={onCancel}>取消</button></div></form>;
}

function WorkflowForm({ projects, skills, pending, error, onSubmit }: { projects: Project[]; skills: SkillSnapshot[]; pending: boolean; error: unknown; onSubmit(input: unknown): void }) {
  const [runtime, setRuntime] = useState("internal");
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const input = workflowRuntimeInput(runtime, data); const skill = skills.find((item) => item.name === data.get("skillName")) ?? null; onSubmit({ kind: "workflow", title: data.get("title"), instructions: data.get("instructions"), executorType: runtime, input, timeoutSeconds: 1800, maxAttempts: 3, lifecycleStatus: "active", projectId: data.get("projectId") || null, skill }); };
  const choices = runtime === "codex" ? projects.filter((item) => item.repositoryPath) : projects;
  return <form className="editor-panel" onSubmit={submit}><div className="form-grid"><Field label="名称"><input name="title" required autoFocus /></Field><Field label="Runtime"><select value={runtime} onChange={(event) => setRuntime(event.target.value)}><option value="internal">Internal</option><option value="process">本地 Python / Node</option><option value="codex">Codex</option><option value="openworker">OpenWorker</option></select></Field><Field label="固定 Skill" hint="保存时会把版本、内容与 SHA-256 一并固化。"><select name="skillName" required={runtime === "codex" || runtime === "openworker"}><option value="">{runtime === "codex" || runtime === "openworker" ? "请选择 Skill" : "不绑定 Skill"}</option>{skills.map((item) => <option value={item.name} key={item.name}>{item.name}@{item.version} · {item.contentHash.slice(0, 10)}</option>)}</select></Field><Field label="所属项目" hint={runtime === "codex" ? "Codex 必须绑定一个已有 Git 仓库的项目。" : "可选；绑定后运行、成果和经营事实会进入项目聚合。"}><select name="projectId" required={runtime === "codex"}><option value="">{runtime === "codex" ? "请选择 Git 项目" : "不绑定项目"}</option>{choices.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Field><Field label="执行要求"><textarea name="instructions" required rows={4} /></Field>{runtime === "internal" ? <Field label="输出消息"><input name="message" defaultValue="执行完成" /></Field> : runtime === "process" ? <><Field label="命令"><select name="command"><option value="python3">python3</option><option value="node">node</option></select></Field><Field label="参数" hint="按空格分隔，不经过 Shell 插值。"><input name="args" /></Field><Field label="工作目录"><input name="cwd" required /></Field></> : runtime === "codex" ? <><Field label="文件权限"><select name="sandboxMode" defaultValue="read-only"><option value="read-only">只读</option><option value="workspace-write">允许修改项目</option></select></Field><Field label="联网能力"><label className="check-field"><input type="checkbox" name="networkAccess" /> 允许网络与网页搜索</label></Field></> : <Field label="OpenWorker Agent"><select name="agent" defaultValue="cowork"><option value="cowork">Cowork</option><option value="code">Code</option></select></Field>}</div><p className="form-note"><LockKeyIcon /> 保存后形成一个不可变 Skill 版本；需要改方法时创建新版本并重新绑定 Schedule。</p>{runtime === "codex" && choices.length === 0 && <p className="form-error">请先创建并绑定一个本地 Git 项目。</p>}{(runtime === "codex" || runtime === "openworker") && skills.length === 0 && <p className="form-error">仓库中没有可用 Skill。</p>}{Boolean(error) && <p className="form-error">{errorMessage(error, "保存失败")}</p>}<button className="button primary" disabled={pending || (runtime === "codex" && choices.length === 0) || ((runtime === "codex" || runtime === "openworker") && skills.length === 0)}>{pending ? "正在保存" : "保存固定版本"}</button></form>;
}

function workflowRuntimeInput(runtime: string, data: FormData): unknown {
  if (runtime === "internal") return { operation: "echo", message: data.get("message") ?? "执行完成", delayMs: 0 };
  if (runtime === "process") return { command: data.get("command"), args: String(data.get("args") ?? "").split(" ").filter(Boolean), cwd: data.get("cwd") };
  if (runtime === "codex") { const networkAccess = data.get("networkAccess") === "on"; return { runtime: { sandboxMode: data.get("sandboxMode") || "read-only", networkAccess, webSearch: networkAccess } }; }
  return { runtime: { agent: data.get("agent") || "cowork" } };
}

function ScheduleForm({ workflows, selectedWorkSpecId, pending, error, onSubmit }: { workflows: WorkSpec[]; selectedWorkSpecId?: string; pending: boolean; error: unknown; onSubmit(input: unknown): void }) {
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); onSubmit({ workSpecId: data.get("workSpecId"), name: data.get("name"), cronExpression: data.get("cronExpression"), timezone: data.get("timezone"), enabled: true, catchUp: data.get("catchUp") === "on" }); };
  return <form className="editor-panel" onSubmit={submit}><div className="form-grid"><Field label="固定 Skill 版本"><select name="workSpecId" defaultValue={selectedWorkSpecId} required>{workflows.map((item) => <option key={item.id} value={item.id}>{item.title} · {item.id.slice(0, 8)}</option>)}</select></Field><Field label="定时名称"><input name="name" required /></Field><Field label="Cron 表达式"><input name="cronExpression" defaultValue="0 8 * * *" required /></Field><Field label="时区"><input name="timezone" defaultValue="Asia/Tokyo" required /></Field><Field label="错过触发"><label className="check-field"><input type="checkbox" name="catchUp" /> 恢复后最多补跑一次</label></Field></div>{workflows.length === 0 && <p className="form-error">请先建立一个雷达固定版本。</p>}{Boolean(error) && <p className="form-error">{errorMessage(error, "保存失败")}</p>}<button className="button primary" disabled={pending || workflows.length === 0}>{pending ? "正在保存" : "保存定时"}</button></form>;
}
